name: Release

on:
  workflow_call:
    inputs:
      github-release:
        required: false
        type: boolean
        default: true
      publish:
        required: false
        type: boolean
        default: false
      build:
        required: false
        type: string
        default: 'pnpm run build'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup JS
        uses: bjf5201/workflows/setup-env@227bf1e1a4222c9b8d69d9b58217d50e82f90354
        with:
          fetch-all: true

      - name: Set GitHub User
        run: |
          git config --global user.name "Bethany Fannin"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate GitHub Changelog
        if: ${{ inputs.github-release }}
        # `--release` argument syncs the changelog and package.json with the GitHub Release
        run: pnpm dlx changelogen@v0.6.2 gh release # changelogen@v0.6.2
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: ${{ inputs.build && inputs.publish }}
        run: ${{ inputs.build }}

      - name: Publish to NPM
        if: ${{ inputs.publish }}
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}