name: CI

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-latest

      os-matrix:
        required: false
        type: string
        default: '"ubuntu-latest", "windows-latest", "macos-latest"'

      node-versions:
        required: false
        type: string
        default: 'lts/*'

      typecheck:
        required: false
        type: string
        default: pnpm run typecheck

      lint:
        required: false
        type: string
        default: pnpm run lint

      build:
        required: false
        type: string
        default: pnpm run build

      test:
        required: false
        type: string
        default: pnpm run test --coverage

      skip-lint:
        required: false
        type: boolean
        default: false

      skip-test:
        required: false
        type: boolean
        default: false

      build-for-lint:
        required: false
        type: boolean
        default: false

jobs:

  test:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: ${{ fromJson(format('[{0}]', inputs.os-matrix)) }}
        node-version: ${{ fromJson(format('[{0}]', inputs.node-versions)) }}
      fail-fast: false

    if: ${{ !inputs.skip-test }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup environment
        uses: bjf5201/workflows/setup-env@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        if: ${{ inputs.build != ''}}
        run: ${{ inputs.build }}

      - name: Test
        run: ${{ inputs.test }}

      - name: Upload coverage reports to Codecov
        if: ${{ !inputs.test == '' || contains(inputs.test, '--coverage') }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          use_oidc: true
          directory: ./coverage


  lint:
    runs-on: ${{ inputs.primary-os }}
    if: ${{ !inputs.skip-lint }}
    steps:
      - name: Setup environment
        uses: bjf5201/workflows/setup-env@v1.0.2
        with:
          primary-os: ${{ inputs.primary-os }}

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build-for-lint }}

      - name: Lint
        run: ${{ inputs.lint }}
        if: ${{ inputs.lint != '' }}

      - name: Type Check
        run: ${{ inputs.typecheck }}
        if: ${{ inputs.typecheck != '' }}


