name: CI

on:
  workflow_call:
    inputs:
      primary-os:
        required: false
        type: string
        default: ubuntu-latest

      os-matrix:
        required: false
        type: string
        default: '"ubuntu-latest", "windows-latest"'

      node-versions:
        required: false
        type: string
        default: '20,22,24,25'

      typecheck:
        required: false
        type: string
        default: pnpm run typecheck

      lint:
        required: false
        type: string
        default: pnpm run lint

      build:
        required: false
        type: string
        default: pnpm run build

      test:
        required: false
        type: string
        default: pnpm run test

      skip-lint:
        required: false
        type: boolean
        default: false

      skip-test:
        required: false
        type: boolean
        default: false

      build-for-lint:
        required: false
        type: boolean
        default: false

jobs:
  lint:
    runs-on: ${{ inputs.primary-os }}
    if: ${{ !inputs.skip-lint }}
    steps:
      - name: Setup environment
        uses: bjf5201/workflows/setup-env@v1.0.2
        with:
          primary-os: ${{ inputs.primary-os }}

      - name: Lint
        run: ${{ inputs.lint }}
        if: ${{ inputs.lint != '' }}

      - name: Type Check
        run: ${{ inputs.typecheck }}
        if: ${{ inputs.typecheck != '' }}

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build-for-lint }}

  test:
    strategy:
      matrix:
        os: ${{ fromJson(format('[{0}]', inputs.os-matrix)) }}
        node-version: ${{ fromJson(format('[{0}]', inputs.node-versions)) }}
      fail-fast: false

    if: ${{ !inputs.skip-test }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JS
        uses: bjf5201/workflows/setup-env@v1.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Unit Test
        run: ${{ inputs.test }}